---

name: Perforce P4 GitHub Actions
author: Andy Boutte <aboutte@perforce.com>
description: Run p4 commands withing your GitHub Actions Workflows

inputs:
  command:
    description: p4 command to execute
    required: true
  global_options:
    description: arguments for p4 cli that go before p4 command
    required: false
  arguments:
    description: arguments for p4 cli that go after p4 command
    required: false
  spec:
    description: This is the P4 spec contents for the resource you are creating
    required: false
  p4_version:
    description: Version of P4 binary to use 
    required: false
    default: 21.2

outputs:
  # stdout:
  #   description: stdout of p4 command
  status:
    description: status code that p4 command exits with

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  color: blue
  icon: package
