---

name: Perforce GitHub Actions
author: Andy Boutte <aboutte@perforce.com>
description: Run p4 commands

inputs:
  command:
    description: command to execute
    required: true
  arguments:
    description: arguments for command
    required: false
  working_directory:
    description: working directory for command (defaults to root)
    required: false


outputs:
  stdout:
    description: stdout of p4 command

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}

branding:
  color: blue
  icon: package
