on: [push]

name: CI

jobs:
  
  shellcheck:
    runs-on: ubuntu-latest
    name: shellcheck

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  p4-info:
    runs-on: ubuntu-latest
    name: p4 info

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: p4 info
        uses: ./
        with:
          command: -V
