on:
  workflow_dispatch:
  push:

name: CI

jobs:

  unit:
    name: unit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  smoke:
    name: smoke
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-10.15, macos-11, windows-2022, windows-2019]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: p4 info 21.1
        uses: ./
        with:
          p4_version: 21.1
          command: -V

      - name: p4 info 21.2
        uses: ./
        with:
          p4_version: 21.2
          command: -V

      - name: p4 info 21.2
        uses: ./
        with:
          p4_version: 21.2
          command: -V

  integration:
    name: integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-10.15, macos-11, windows-2022, windows-2019]

    env:
      P4PORT: ${{ secrets.P4PORT }}
      P4USER: ${{ secrets.P4USER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: p4 login
        uses: ./
        id: login
        with:
          command: login
        env:
          P4PASSWD: ${{ secrets.P4PASSWD }}

      - name: p4 client
        uses: ./
        id: client
        with:
          command: client
          arguments: -i

          spec: |
            Client:	github-actions-setup-p4
            Owner: ${{ secrets.P4USER }}
            Description:
              Created by ${{ secrets.P4USER }}.
            Root:	/tmp
            Options:	noallwrite noclobber nocompress unlocked modtime rmdir
            SubmitOptions:	leaveunchanged
            LineEnd:	local
            View:
              //guest/perforce_software/sdp/... //github-actions-setup-p4/guest/perforce_software/sdp/...

      - name: p4 sync
        uses: ./
        id: sync
        env:
          P4CLIENT: github-actions-setup-p4
        with:
          command: sync
          arguments: -f
