on: [push]

jobs:
  internal:
    runs-on: ubuntu-latest
    name: test private action
    env:
      P4PORT: public.perforce.com:1666
      P4USER: andy_boutte
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: p4 login
        uses: ./ # Uses an action in the root directory
        id: login
        with:
          command: login
          pre_command_arguments: '-p public.perforce.com:1666 -u andy_boutte'
          # post_command_arguments: '-v'
        env:
          P4_PASSWORD: ${{ secrets.P4_PASSWORD }}

      - name: p4 depots
        uses: ./ # Uses an action in the root directory
        id: depots
        with:
          command: depots

      - name: p4 clients
        uses: ./ # Uses an action in the root directory
        id: clients
        with:
          command: clients

      - name: p4 client
        uses: ./ # Uses an action in the root directory
        id: client
        with:
          command: client
          post_command_arguments: -i

          spec: |
            Client:	sdp-dev-pipeline

            Update:	2021/11/18 06:10:36

            Access:	2022/01/20 17:15:32

            Owner:	andy_boutte

            Description:
              Created by andy_boutte.

            Root:	/tmp

            Options:	noallwrite noclobber nocompress unlocked modtime rmdir

            SubmitOptions:	leaveunchanged

            LineEnd:	local

            View:
              //guest/perforce_software/sdp/... //sdp-dev-pipeline/guest/perforce_software/sdp/...
              //guest/perforce_software/helix-installer/... //sdp-dev-pipeline/guest/perforce_software/helix-installer/...


      - name: p4 sync
        uses: ./ # Uses an action in the root directory
        id: sync
        env:
          P4CLIENT: sdp-dev-pipeline
        with:
          command: sync
          post_command_arguments: -f

